# Generated by Django 3.1 on 2020-08-06 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsUsers',
            new_name='NewsUser',
        ),
    ]
