# Generated by Django 3.0.8 on 2020-07-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(verbose_name='birthdate'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(max_length=50, verbose_name='fullname'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='postcode',
            field=models.CharField(max_length=20, verbose_name='postcode'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='street_address2',
            field=models.CharField(blank=True, max_length=40, verbose_name='street address 2'),
        ),
    ]
