# Generated by Django 3.0.8 on 2020-07-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='productimage',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
