# Generated by Django 3.0.8 on 2020-07-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200727_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='name',
            field=models.ImageField(upload_to='images'),
        ),
    ]
